const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const source = fs.readFileSync('extensions/dola30/service-worker-v2.js', 'utf8');
const context = vm.createContext({console});
vm.runInContext(source.slice(source.indexOf('function patchActionBarDuration('), source.indexOf('function findImageOriRawUrls(')), context);
const dropdown = {key:'video-duration', option_list:[{id:1,option_key:'5',display_text:'5s'},{id:2,option_key:'10',display_text:'10s'}]};
const slider = {key:'video-duration',lower_bound:4,upper_bound:10,step_length:1,default_selected_duration:10};
const unrelated = {key:'page_size',label:'\u9577\u3055',option_list:[{option_key:'5',display_text:'5'},{option_key:'10',display_text:'10'}],lower_bound:4,upper_bound:10};
const body = JSON.stringify({direct:slider,template:JSON.stringify({selector_list:[dropdown,slider,unrelated]}),unrelated});
const result = context.patchActionBarDuration(body);
const parsed = JSON.parse(result), nested=JSON.parse(parsed.template);
assert.equal(parsed.direct.upper_bound,30);
assert.equal(parsed.direct.lower_bound,4);
assert.equal(parsed.direct.step_length,1);
assert.equal(parsed.direct.default_selected_duration,10);
assert.deepEqual(nested.selector_list[0].option_list.map(x=>x.option_key),['5','10','30']);
assert.equal(nested.selector_list[1].upper_bound,30);
assert.deepEqual(nested.selector_list[2],unrelated);
assert.deepEqual(parsed.unrelated,unrelated);
assert.equal(context.patchActionBarDuration(result),result);
assert.equal(context.patchActionBarDuration('not json'),'not json');
console.log('PASS direct/nested dropdown + slider, unrelated controls, idempotency');
